### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at /usr/src/backends/src/lib.rs:176:14

### ISSUE THREAD

**Issue by jackli0127** [huggingface/text-embeddings-inference#424]
### System Info

image: ghcr.io/huggingface/text-embeddings-inference:86-1.5

Docker restarted and output the following error log:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2024-10-13T19:18:24.970Z | thread 'tokio-runtime-worker' panicked at /usr/src/backends/src/lib.rs:176:14:
2024-10-13T19:18:24.970Z | No backend receiver. This is a bug.: "Full(..)"
2024-10-13T19:18:24.970Z | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace



### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

2024-10-13T19:18:24.970Z | thread 'tokio-runtime-worker' panicked at /usr/src/backends/src/lib.rs:176:14:
2024-10-13T19:18:24.970Z | No backend receiver. This is a bug.: "Full(..)"
2024-10-13T19:18:24.970Z | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Expected behavior

Keep Docker running, don't restart.

**Comment by jackli0127** [comment]
No other error logs can be found, only some info level logs.

![image](https://github.com/user-attachments/assets/05e710f1-d2ee-4d52-b783-0ac82a79e145)

**Comment by eli-persona** [comment]
We;re also seeing this error,  FWIW;  also no additional helpful diagnostics or evidence to explain why this might happen.

- `ghcr.io/huggingface/text-embeddings-inference:1.6`
- `intfloat/multilingual-e5-large` model
- Hardware details: we're running on an A100 split into 1g.5gb MIG profiles.

**Comment by touhi99** [comment]
any update on the issue if there's a fix? still finding same error on 1.7-cpu

**Comment by snowch** [comment]
We hit this panic in production and have a **deterministic reproduction** on the stock image, plus what we believe is the mechanism. Posting both since the issue has been open a while without a repro.

```
thread 'tokio-runtime-worker' panicked at backends/src/lib.rs:176:14:
No backend receiver. This is a bug.: "Full(..)"
```
Container exits **139**, `OOMKilled=false`.

## Mechanism

`Backend::health()` has two branches (`backends/src/lib.rs`):

```rust
pub async fn health(&self) -> Result<(), BackendError> {
    if *self.health_receiver.borrow() {
        // healthy: send().await — waits for capacity, cannot panic
        self.backend_sender.send(BackendCommand::Health(..)).await
    } else {
        // unhealthy: "a more advanced health check by calling the model forward"
        ModelType::Embedding(_) => self.embed(batch).await   // -> try_send
    }
}
```

and `embed()` / `predict()` use a bare `try_send` on a channel created as `mpsc::channel(8)`:

```rust
self.backend_sender
    .try_send(BackendCommand::Embed(batch, Span::current(), sender))
    .expect("No backend receiver. This is a bug.");
```

The health flag is **not sticky** — `BackendThread` republishes it after *every* command:

```rust
let mut healthy = false;            // reset each iteration
    ... healthy = true;             // only if THAT command succeeded
let _ = health_sender.send(healthy);
```

So one failed backend operation flips it to `false`, and the next `/health` probe takes the `else` branch and `try_send`s onto a channel that is full *because* the backend is struggling. **The unhealthy path is only reachable when the server is already in trouble, and that is the path that panics the process.**

`backend_task` (`core/src/infer.rs`) awaits each embed and so contributes at most one queued command — the overflow comes from concurrent health probes in the unhealthy window. In Kubernetes, liveness and readiness probes supply exactly that.

## Reproduction

Stock image, public model, TEI's default flags, Python stdlib only.

```bash
# 1. stage the model (cpu-1.x needs the ONNX export)
B=https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main
mkdir -p tei-data/model/onnx tei-data/model/1_Pooling
for f in config.json tokenizer.json tokenizer_config.json special_tokens_map.json \
         vocab.txt model.safetensors 1_Pooling/config.json onnx/model.onnx; do
    curl -sSL -o "tei-data/model/$f" "$B/$f"
done

# 2. constrained CPU *and* memory — both are load-bearing, see below
docker run -d --name tei-repro --cpus=1 --memory=900m --memory-swap=900m \
  -p 18090:80 -e HF_HUB_OFFLINE=1 -v "$PWD/tei-data:/data" \
  ghcr.io/huggingface/text-embeddings-inference:cpu-1.5 --model-id /data/model --port 80

# 3. saturate, then probe /health concurrently
python3 tei_panic_repro.py
```

Observed:
```
wave 4-6:  TimeoutError        <- saturated
wave 7:    RemoteDisconnected  <- panic lands mid-request
wave 8:    URLError, up=False  <- process gone
```

## What does NOT reproduce it

Worth stating, because these are the obvious attempts and all three are negative — which is probably why this has looked random:

| attempt | result |
| --- | --- |
| sustained load alone | **wedges** — `/health` stops answering while `/embed` still returns 200. No panic. |
| concurrent `/health` storm alone | every probe times out on the **safe** branch. No panic. |
| storming `/health` at startup | TEI's own warmup flips the flag `true` first. No panic. |

**Memory pressure is the missing ingredient**: it makes a backend operation *fail*, which is what flips the flag false. Without it the panicking branch is never entered.

## A note on the message

`try_send` fails with either `Full` (receiver alive, behind) or `Closed` (receiver gone). *"No backend receiver"* describes `Closed` — but every report of this, including ours, carries `Full(..)`. The `expect` was written for the case its author took to be unreachable, and fires on the one that isn't, which is why the message hasn't helped anyone diagnosing it.

## Proposed fix — NOT YET VERIFIED

Flagging clearly: we have **not** built and tested this. `ErrorType::Overloaded` already exists and is already wired to a 429 for the semaphore path, so `Full` has somewhere sensible to go:

```rust
self.backend_sender
    .try_send(BackendCommand::Embed(batch, Span::current(), sender))
    .map_err(|e| match e {
        TrySendError::Full(_)   => BackendError::Overloaded,   // 429 — alive, behind
        TrySendError::Closed(_) => BackendError::NoBackend,    // what the message meant
    })?;
```

plus the same in `predict()`, and the unhealthy branch of `health()` not routing through a panicking send.

Happy to open a PR if that direction looks right — and happy to test any alternative you prefer against the reproduction above, which is the part that was missing.

[tei_panic_repro.py](https://github.com/user-attachments/files/31377412/tei_panic_repro.py)

---



Correcting and **strengthening** one claim in my comment above. I said the panicking path *"is only reachable once the server is already in trouble."* That is wrong, and the true version is worse.

**The unhealthy branch runs on every boot, before the listener exists.** `router/src/lib.rs`, strict sequential awaits:

```
:252  backend.health().await          <- nothing has flipped health_receiver yet
:256  backend.warmup(...).await
:337  http::server::run(...)          <- the listener only exists HERE
```

and `health_receiver` is `watch::channel(false)` (`backends/src/lib.rs:61`), so at `:252` `health()` takes the `else` branch — `self.embed(batch)` — which is the bare `try_send(...).expect("No backend receiver. This is a bug.")`.

**So `try_send().expect()` is on the normal startup path of every single process.** It is safe there only because the channel happens to be empty at that instant. Nothing enforces that invariant. Any change that lets work queue before `:252` — a concurrent readiness probe, a warmup that enqueues, a retry — turns a path every boot already takes into a guaranteed crash.

That is a **latent** defect alongside the live one, and I think it is the stronger argument for a bounded `send()`: not *"it crashes when degraded"* but *"it is safe by accident on a path we always take."*

**This also explains a negative result, in case anyone tries the same thing.** We attempted to reach the branch through the benign pre-warm window — the server is genuinely unhealthy before any command succeeds, so no induced failure should be needed. It does not work: the port does not accept until `warmup()` at `:256` has already returned, so by the time a client can connect a command has succeeded and the flag is true. **The window is shut before the door opens.** Any apparent gap between "port accepts" and "first 200" measured through a Docker published port is docker-proxy, not the server.

**One more site, same class, which a fix should probably cover.** One line below the `try_send` in each of `embed()`, `predict()` and `health()`:

```rust
receiver.await.expect(
    "Backend blocking task dropped the sender without send a response. This is a bug.")
```

`BackendThread`'s loop is `while let Some(cmd) = backend_receiver.blocking_recv()`. If that thread ever exits, every in-flight `oneshot::Sender` drops and every awaiting caller panics here instead. Mapping `Full` to a 429 cannot save a process whose backend thread has gone, so the two are worth fixing together.

Still **unverified** on our side: we built the `Full → Overloaded → 429` patch and it compiles and serves, but instrumenting the branch shows it has never actually executed in our runs (0 hits), so we cannot yet claim it works. Reporting that rather than sitting on it, since the reproduction above is the part we are confident in.

**Comment by snowch** [comment]
# Proposed fix for #424 — `try_send(...).expect(...)` kills the process under backpressure

Against **v1.5.0 (`661a77f`)**. Three files, 18 lines. Patch: `tei-424-upstream.patch`.

## The bug

`Backend::health()` has two branches (`backends/src/lib.rs:132`). The **healthy** branch uses
`send().await` — it blocks when the channel is full and is safe. The **unhealthy** branch calls
`self.embed(batch)`, and `embed()`/`predict()` use a bare
`try_send(...).expect("No backend receiver. This is a bug.")` on `mpsc::channel(8)`.

The health flag is **not sticky**: `BackendThread` republishes it after every command
(`backends/src/lib.rs:250`), resetting to `false` and setting `true` only if *that* command
succeeded. So one failed backend operation re-arms the trap, and the next `/health` probe takes
the unhealthy branch and `try_send`s onto a channel that is full *because* the backend is
struggling.

**The recovery path is what kills the process, and it is only reachable when the server is
already in trouble.** With `panic = "abort"` in `[profile.release]`, that panic is immediately
fatal — the observed exit is 139, not Rust's usual 101.

Note the message is wrong for the case that actually fires: `try_send` fails with `Full`
(receiver alive, behind) or `Closed` (receiver gone). *"No backend receiver"* describes `Closed`,
but every report of this, including ours, carries `Full(..)`. The `expect` was written for the
case its author took to be unreachable and fires on the one that isn't.

## The fix

Map the two variants to distinct errors instead of panicking:

```rust
.map_err(|err| match err {
    mpsc::error::TrySendError::Full(_)   => BackendError::Overloaded,  // alive, behind -> 429
    mpsc::error::TrySendError::Closed(_) => BackendError::NoBackend,   // gone -> 424
})?;
```

### Why 429, and why this is not a new convention

`ErrorType::Overloaded` **already exists** (`router/src/lib.rs:516`) and upstream already maps it
`=> StatusCode::TOO_MANY_REQUESTS` (`http/server.rs:1794`) and `=> Code::ResourceExhausted`
(`grpc/server.rs:1534`). The patch touches neither mapping and gets gRPC parity for free. The
`/predict` OpenAPI block already documents 429 *"Model is overloaded"*.

Decisively: your existing overload type is `Overloaded(#[from] TryAcquireError)`
(`core/src/lib.rs:17`) — a non-blocking attempt on a bounded resource, rejected at the bound.
That is `TrySendError::Full` exactly, one layer down. **503 would be the novel choice here, not
429.**

`Closed` deliberately does **not** become 429: the backend thread is dead, and telling a client
to retry would be a lie about a server that cannot recover. `NoBackend` → 424 is honest.

## Evidence

Reproduction: `tei_panic_repro.py` (posted earlier in this issue) — stock upstream image, public
90 MB model, Python stdlib only, no vendor-specific infrastructure.

Two builds from this source differing by **one line** in the `Full` arm, confirmed as a
single-variable difference in the compiled binaries before running:

| build | `Full` arm | reached `Full` | panicked | outcome |
|---|---|---|---|---|
| control | `panic!` (upstream behaviour) | yes | **yes** | `exit 139` |
| patched | `BackendError::Overloaded` | yes, repeatedly | **no** | serving, clients get 429 |

The patched build was then exercised **unmodified, at the real `mpsc::channel(8)`**, and returned:

```
HTTP 429  {"error":"Backend error: Model is overloaded","error_type":"Overloaded"}
```

The `"Backend error: "` prefix (`core/src/lib.rs:18`) distinguishes this from the pre-existing
semaphore path at `:16`, which renders the same text without a prefix — so these 429s are the
patched arm and not existing behaviour.

**Also observed on a real deployment** (4 CPU / 20 GiB, not the constrained reproduction): the
identical panic at `backends/src/lib.rs:176`, `Full(..)`, `exit 139`, preceded by `queue_time`
climbing to 36–59 s sustained. A second instance of the same image under light load reached a
similar *peak* queue time but never sustained it and never panicked — the trigger is sustained
saturation, not a spike.

## Scope — what is and is not tested

* **The `Full` arm is exercised** — it is the arm that fires in practice and the one every report
  carries.
* **The `Closed` arm is NOT exercised.** Reaching it requires the backend thread to die, which our
  harness never induced. It is included because leaving `Closed` panicking would fix half of a
  two-variant match, but I would not claim it tested.
* **This patch does not touch `receiver.await.expect(...)`**, which sits one line below at all
  three call sites. If `BackendThread` exits, in-flight callers still panic there. That is a
  separate defect and arguably a separate PR; flagging it so the scope of this one is clear.

[tei424upstream.patch](https://github.com/user-attachments/files/31382815/tei424upstream.patch)
