### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at /usr/src/router/src/server.rs:418:60: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by eureka43** [huggingface/text-embeddings-inference#91]
### System Info

docker : ghcr.io/huggingface/text-embeddings-inference:turing-0.5
model: [BAAI/bge-reranker-large](https://huggingface.co/BAAI/bge-reranker-large)

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [x] An officially supported command
- [ ] My own modifications

### Reproduction

1. docker run --gpus all -e RUST_BACKTRACE=full -p 8080:80 -v /reranker_model:/reranker_model  --rm  ghcr.io/huggingface/text-embeddings-inference:turing-0.5 --model-id /reranker_model  --revision refs/pr/4
2. test with:
```c
curl --location 'http://127.0.0.1:8080/rerank' \
--header 'Content-Type: application/json' \
--data '{
    "query":"What is Deep Learning?",
    "texts": ["Deep Learning is not...", "Deep learning is..."]
}'
```

3. output:

```
thread 'tokio-runtime-worker' panicked at /usr/src/router/src/server.rs:418:60:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x5628b57586fc - std::backtrace_rs::backtrace::libunwind::trace::he43a6a3949163f8c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5628b57586fc - std::backtrace_rs::backtrace::trace_unsynchronized::h50db52ca99f692e7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5628b57586fc - std::sys_common::backtrace::_print_fmt::hd37d595f2ceb2d3c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5628b57586fc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5628b57850cc - core::fmt::rt::Argument::fmt::h3a159adc080a6fc9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:     0x5628b57850cc - core::fmt::write::hb8eaf5a8e45a738e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:     0x5628b5754f3e - std::io::Write::write_fmt::h9663fe36b2ee08f9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:     0x5628b57584e4 - std::sys_common::backtrace::_print::hcd4834796ee88ad2
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5628b57584e4 - std::sys_common::backtrace::print::h1360e9450e4f922a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5628b5759c53 - std::panicking::default_hook::{{closure}}::h2609fa95cd5ab1f4
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:     0x5628b575996c - std::panicking::default_hook::h6d75f5747cab6e8d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
  11:     0x5628b575a1d9 - std::panicking::rust_panic_with_hook::h57e78470c47c84de
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
  12:     0x5628b575a091 - std::panicking::begin_panic_handler::{{closure}}::h3dfd2453cf356ecb
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:597:13
  13:     0x5628b5758c26 - std::sys_common::backtrace::__rust_end_short_backtrace::hdb177d43678e4d7e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x5628b5759e22 - rust_begin_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
  15:     0x5628adcb5a83 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
  16:     0x5628adcb5b13 - core::panicking::panic::hd907d42d09324a32
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
  17:     0x5628ae03e858 - core::option::Option<T>::unwrap::h6470a221343dc423
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/option.rs:935:21
  18:     0x5628ae03e858 - text_embeddings_router::server::rerank::{{closure}}::{{closure}}::{{closure}}::h8528c3cca2034e24
                               at /usr/src/router/src/server.rs:418:30
  19:     0x5628ae03e858 - alloc::slice::<impl [T]>::sort_by::{{closure}}::h30bf7b47df7e6c75
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/slice.rs:267:34
  20:     0x5628ae03e858 - core::slice::sort::insert_tail::had23d4840d83b632
  21:     0x5628ae03e858 - core::slice::sort::insertion_sort_shift_left::h8e40fc858f60e7aa
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/slice/sort.rs:163:13
  22:     0x5628ae0788b9 - alloc::slice::stable_sort::h1d9cc0e7d6b8669f
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/slice.rs:887:5
  23:     0x5628ae0788b9 - alloc::slice::<impl [T]>::sort_by::hd6c2cbc4000ec05b
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/slice.rs:267:9
  24:     0x5628ae0788b9 - text_embeddings_router::server::rerank::{{closure}}::{{closure}}::h19ff20c74d1989c7
                               at /usr/src/router/src/server.rs:418:9
  25:     0x5628ae0788b9 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::hd32e869d8ff10e8a
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  26:     0x5628ae128737 - text_embeddings_router::server::rerank::{{closure}}::h9e2ede4e62dfd11f
                               at /usr/src/router/src/server.rs:294:1
  27:     0x5628ae128737 - <F as axum::handler::Handler<(M,T1,T2,T3),S,B>>::call::{{closure}}::h9c7aaf5ba3fb7bd7
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-0.6.20/src/handler/mod.rs:248:53
  28:     0x5628adfe4231 - <core::pin::Pin<P> as core::future::future::Future>::poll::h794832362a0629a1
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/future/future.rs:125:9
  29:     0x5628ae16f397 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::ha7b462b7c30f1b59
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.29/src/future/future/map.rs:55:37
```

### Expected behavior

all correct

**Comment by OlivierDehaene** [comment]
I'm unable to reproduce the issue both with `USE_FLASH_ATTENTION=True` and `USE_FLASH_ATTENTION=False`.
Can you share the output of `nvidia-smi`?

**Comment by eureka43** [comment]
> I'm unable to reproduce the issue both with `USE_FLASH_ATTENTION=True` and `USE_FLASH_ATTENTION=False`. Can you share the output of `nvidia-smi`?

![image](https://github.com/huggingface/text-embeddings-inference/assets/141915686/2eeff374-a031-4bb3-be32-510ecfe65217)

**Comment by Loovelj** [comment]
@eureka43  Hello,Did you slove it?

**Comment by eureka43** [comment]
@Loovelj  nope, I tried another type GPU--A6000, it's ok.
